version: "3.7"

networks:
  restheart_network:

volumes: 
  mongo_data:
    external: true

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./store/esdata1:/usr/share/elasticsearch/data
      - ./store/logs:/var/log
    networks:
      - restheart_network
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./store/esdata2:/usr/share/elasticsearch/data
      - ./store/logs:/var/log
    networks:
      - restheart_network
    ports:
      - 9201:9200
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./store/esdata3:/usr/share/elasticsearch/data
      - ./store/logs:/var/log
    networks:
      - restheart_network
    ports:
      - 9202:9200

  gateway:
    build: ./gateway
    image: binhthvuejx/gateway
    container_name: gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway/:/app
    networks:
      - restheart_network
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - SERVICE_SECURITY=http://vuejx-core-prod:3000
      - SERVICE_RESTHEART=http://restheart:8080
      - SECREST_KEY=VnVlSlggQmluaHRoIDEyNTQ1ODEyOSBWdWVqcyBWdWV0aWZ5anM=
      - CLUSTER_NODE=2

  security:
    image: binhth/security
    build: ./restheart-security
    container_name: security
    volumes:
      - ./restheart-security/:/app
    depends_on:
      - mongodb
    networks:
      - restheart_network
    ports:
      - "3001:3000"
    expose:
      - 3000
    environment:
      - SERVICE_NAME=security
      - WAIT_HOSTS=vuejx-core-prod:3000
      - WAIT_HOSTS_TIMEOUT=600
      - MONGO_HOSTS=mongodb:27017
      - MONGO_INITDB_OAUTH2_USERNAME=oauth2_user
      - MONGO_INITDB_OAUTH2_PASSWORD=123456Aa
      - MONGO_INITDB_DATABASE=oauth2
      - SECREST_KEY=VnVlSlggQmluaHRoIDEyNTQ1ODEyOSBWdWVqcyBWdWV0aWZ5anM=
      - EXPIRY_DATE=6h
      - CLUSTER_NODE=2
    labels: 
      - api_route=/security
  
  restheart:
    image: softinstigate/restheart:latest
    build: ./restheart-core
    container_name: restheart
    depends_on:
      - mongodb
    networks:
      - restheart_network
    ports:
      - "8081:8080"
    expose:
      - 8080
    environment:
      - SERVICE_NAME=restheart
    labels: 
      - api_route=/core
      
  vuejx-core-prod:
    build: ./vuejx-core-prod
    container_name: vuejx-core-prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./store/logs/vuejx-core-prod:/log
      - ./vuejx-core-prod/:/app
    networks:
      - restheart_network
    ports:
      - "3002:3000"
    expose:
      - 3000
    environment:
      - SERVICE_NAME=vuejx
      - WAIT_HOSTS=elasticsearch:9200
      - MONGO_INITDB_OAUTH2_USERNAME=oauth2_user
      - MONGO_INITDB_OAUTH2_PASSWORD=123456Aa
      - PROJECT_SERVICE_HOST=http://restheart:8080
      - SECURITY_SERVICE_HOST=http://security:3000
      - WAIT_HOSTS_TIMEOUT=600
      - NODE_ENV=development
      - SECREST_KEY=VnVlSlggQmluaHRoIDEyNTQ1ODEyOSBWdWVqcyBWdWV0aWZ5anM=
      - EXPIRY_DATE=6h
      - CLUSTER_NODE=2
    labels: 
      - api_route=/vuejx

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: restheart
      MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
      MONGO_INITDB_DATABASE: vuejx_cfg
      MONGO_REPLICA_SET_NAME: rs0
      SERVICE_NAME: mongodb
    labels: 
      - api_route=/mongodb
    command: ["--auth", "--bind_ip_all", "--replSet", "rs0"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u restheart -p R3ste4rt! --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - mongo_data:/data/db
      - ./store/mongodb/:/data_backup
    networks:
      - restheart_network
    ports:
      - "27017:27017"
    expose:
      - 27017
  
  oauth2-client-prod:
    build: ./oauth2-client-prod
    container_name: oauth2-client-prod
    ports:
      - 8800:8800
    expose:
      - 8800
    environment:
      - SERVICE_NAME=oauth2-client-prod
      - HOST=0.0.0.0
      - HOSTLOCAL=localhost
      - PORT=8800
      - CLUSTER_NODE=2
    labels:
      - api_route=/login
    command: sh -c "npm install && node server.js"
    volumes:
      - ./oauth2-client-prod/:/app
    networks:
      - restheart_network

  vuejx-client-prod:
    build: ./vuejx-client-prod
    container_name: vuejx-client-prod
    ports:
      - 8801:8801
    expose:
      - 8801
    environment:
      - SERVICE_NAME=vuejx-client-prod
      - HOST=0.0.0.0
      - HOSTLOCAL=localhost
      - PORT=8801
      - ./vuejx-client-prod/:/app
      - CLUSTER_NODE=2
    labels: 
      - api_route=/ui
    command: sh -c "npm install && npm start"
    volumes:
      - ./vuejx-client-prod/:/app
    networks:
      - restheart_network